#! /usr/bin/env bash

if [[ -z $2 ]]; then
    echo -e "=========================================================="
    echo -e "Pass in a project directory and a parameter of a, b, or c."
    echo -e " a) Run Client Server"
    echo -e " b) Run Server"
    echo -e " c) Start Service"
    echo -e "=========================================================="
    exit
fi

function runClientServer() {
    cd $1
    try-run-both build
    cd ..
}

function runServer() {
    cd $1/client
    pwd
    ./build-copy-worker a
    cd ../server
    nohup node bin/www &
    firefox http://localhost:${2}
}

function startService() {
    cd $1/server
    pwd
    ./run-setup-service
}

case $2 in
    [Aa]* ) runClientServer; shift;;
    [Bb]* ) runServer ${1} ${3}; shift;;
    [Cc]* ) startService; shift;;
esac
