#! /bin/bash

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color


# You should define the following environment variables.
# Then run: source setup-environment-service
export SYSTEMD_PROJECT_NAME=midterm
export SYSTEMD_DESCRIPTION="Midterm Service"
export SYSTEMD_PORT="MIDTERM_PORT=30035"

# This export does not need to be edited. It is derived from the lines above.
export SERVICE_FILE=$SYSTEMD_PROJECT_NAME.service

# Describe environment
echo "You set the following environment variables"
echo -e "SYSTEMD_PROJECT_NAME is set to: $BLUE$SYSTEMD_PROJECT_NAME$NC"
echo -e "SERVICE FILE is set to $BLUE$SERVICE_FILE$NC"
echo -e "DESCRIPTION is set to $BLUE$SYSTEMD_DESCRIPTION$NC"
echo -e "SYSTEMD_PORT is set to $BLUE$SYSTEMD_PORT$NC"
echo -e "Renaming$YELLOW temp.service$NC to $YELLOW$SYSTEMD_PROJECT_NAME.service"$NC

mv temp.service $SYSTEMD_PROJECT_NAME.service

echo -e "If the above looks good, run ./mod-service"


function banner {
    echo ' '
    echo ===============================
    echo --- "$1" ---
    echo ===============================
}

function show {
    banner "$1"
    sudo systemctl show -p ActiveState -p SubState -p Environment $2
}

function showSystemCheck() {
    show 'SystemCheck' systemcheck.service
}


function checkPorts() {
    sudo nmap -p 30025-30035 192.168.2.13
}

message 'System Service Control'
T
echo 'Learn about Systemd and other running services.'

while true; do
    message "Menu"    
    echo -e "$LIGHT_GREEN  a) Check Ports 30025-30040"
    echo -e "$LIGHT_GREEN  b) Only Build"
    echo -e "$LIGHT_GREEN  c) Only Delete"
    echo -e "$LIGHT_RED  x) Exit"
    echo -e "\n$NC"
    read -p "Please make a selection: " userInput
    case $userInput in
        [Aa]* ) checkPorts false; continue;;
        [Bb]* ) showSystemCheck; continue;;
        [Cc]* ) deleteOld; continue;;
        [XxQq]* ) break;;
        *) echo -e "\n$NC" + "Please answer with a, b, c, or x.";;
    esac
done
